int get_data();
void sort_data();
int state_color();
int print_object(char match[], int state, int type);
size_t write_data(void *ptr, size_t size, size_t nmemb, void *stream);
char *match_string(char line[], int type);
int get_problems();
extern int reset_vars;
extern int last_type;
int longest_string;
void read_arguments(char path[]);
void count_strings();
int get_conf();
int read_conf(char path[]);
int look_for_conf(char path[], int cvalue);
extern char passwd[256];
extern char server_address[256];
extern char user_pwd[256];
char **get_excludes();
char **excludes_save;
int num_strings;
int get_arguments(int argc, char **argv);
